---
- name: Run Python script
  hosts: "{{ target_hosts }}"
  gather_facts: false
  vars:
    script_name: /tmp/script.py
  tasks:
    - name: Run Python script asynchronously
      ansible.builtin.command:
        cmd: python3 -u "{{ script_name }}"
      async: 3600
      poll: 0
      register: async_job
    - name: Stream script output
      ansible.builtin.shell: tail -f /tmp/count_output.log
