- name: Run Python script and stream output
  hosts: "{{ target_hosts }}"
  gather_facts: false
  vars:
    script_name: /tmp/script.py
  tasks:
    - name: Run Python script
      ansible.builtin.command:
        cmd: python3 -u "{{ script_name }}"
      register: script_output
      async: 3600
      poll: 1  # Poll until done
      # stdout will be streamed to Jenkins via Ansible output
