- name: Run Python script and stream output
  hosts: "{{ target_hosts }}"
  gather_facts: false
  vars:
    script_name: /tmp/script.py
  tasks:
    - name: Run Python script
      ansible.builtin.shell: python3 -u "{{ script_name }}" | tee /tmp/script.log
